### ISSUE TITLE
Task 4 (G): Elaborar un informe gráfico (charting report).

### ISSUE THREAD

**Issue by alepervaz** [alepervaz/Acme-L3-D01#4]
Un informe gráfico es un documento que representa de manera visual la información de un proyecto o equipo de trabajo. Este informe suele incluir gráficos, tablas y diagramas para presentar la información de una manera clara y fácil de entender.

El contenido de un informe gráfico debe incluir un resumen que describa cómo los miembros del equipo fueron reclutados por el gerente. Además, para cada miembro del equipo, debe incluir sus datos de contacto, una declaración en la que todos se comprometan a trabajar juntos y alcanzar una nota determinada, y uno o varios indicadores de rendimiento que midan su desempeño en el trabajo.

El informe también debe incluir una descripción de cómo se recompensará a los miembros del equipo que realicen un buen trabajo y cómo se castigará a aquellos que no lo hagan. Además, debe incluir una declaración sobre las condiciones en las que un miembro del equipo puede ser despedido y las opciones disponibles para los miembros despedidos.

Es importante que el informe esté fechado y firmado por todos los miembros del equipo para garantizar la transparencia y la responsabilidad de cada uno de ellos. En resumen, un informe gráfico es una herramienta valiosa para presentar de manera clara y concisa la información sobre el trabajo y el rendimiento de un equipo.

**Comment by alesanfe** [comment]
Falta el resumen.
